// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.Collections.Generic;
namespace MVCRegistrationform
{

    // RegistrationDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.19.3.0")]
    public class RegistrationDetail
    {
        public string Name { get; set; } // Name (length: 50)
        public string Email { get; set; } // Email (length: 50)
        public string Phone { get; set; } // Phone (length: 50)
        public string Address { get; set; } // Address (length: 2147483647)
        public int Id { get; set; } // ID (Primary key)

    }

}
// </auto-generated>
